import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import './globals.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: {
    template: '%s | Acme Dashboard',
    default: 'Acme Dashboard',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        // antialiased 使得字体在支持 WebKit 的浏览器中显示得更加平滑。
        className={cn(
          'bg-background font-sans antialiased light',
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
